### ISSUE TITLE
Failing tests which are ignored should not cause subsequent tests to fail

### ISSUE THREAD

**Issue by thecapdan** [BladeRunnerJS/continuable-mocha#1]
For example:

```
xit('ignored dummy test 1', function() {
        recordTest(this);
        expect(false).to.be.true;
    });

it('dummy test that continues from ignored dummy test 1', function() {
        continueFrom('ignored dummy test 1');
        recordTest(this);
    });
```

The second test should pass

**Comment by andy-berry-dev** [comment]
@thecapdan does this exact scenario work with the current GWT test runner or is it only when `given,when,then` style is used? i.e. is it specific to `then` blocks being ignored/not run or are any exceptions or failures in the test that we're continuing from caught and ignored?

**Comment by thecapdan** [comment]
hi @andyberry88 , good thing you asked, when I went back to check, the use case i described above, i noticed it doesn't work in the old framework either. So if a test that's being continued from fails, the subsequent test will also fail, which is probably the correct behaviour. So I'll delete this issue

**Comment by andy-berry-dev** [comment]
:+1:
